#!/bin/bash
set -e

NOT_GIT='-not -name .git'
NOT_RUN='-not -name run'
NOT_DOT='-mindepth 1'
NOT_ALL='-maxdepth 1'
NOT_README='-not -name README.md'
RELEVANT="$NOT_DOT $NOT_ALL $NOT_GIT $NOT_RUN $NOT_README"

show () {
  echo $1
  find $PWD $RELEVANT -execdir echo '  ' $HOME/{} \;
  echo
}

case $1 in
  install)
    show "Installing:"
    set -x
    find $PWD $RELEVANT -exec ln -s {} $HOME/. \;
    ;;
  clean)
    if [ "$2" != "-f" ]
    then
      show "Would remove:"
      echo "If you're sure about thisk run again with -f"
      exit 1
    else
      show "Removing:"
      set -x
      find $PWD $RELEVANT -execdir rm -f $HOME/{} \;
    fi
    ;;
  *)
    echo "usage: $0 [ clean | install ]"
    ;;
esac
