#!/bin/bash
set -e

clean () {
  set -x
  find $PWD/home -mindepth 1 -maxdepth 1 -execdir rm -f $HOME/{} \;
}

install () {
  set -x
  find $PWD/home -mindepth 1 -maxdepth 1 -exec ln -s {} $HOME/. \;
}

case $1 in
  reinstall) clean; install ;;
  install)   install ;;
  clean)     clean ;;
  *)         echo "usage: $0 [ clean | install | reinstall ]" ;;
esac
