;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        electric-newline-and-maybe-indent
        indent-new-comment-line
        kill-region
        paredit-backward
        paredit-backward-down
        paredit-backward-kill-word
        paredit-backward-up
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-forward-up
        paredit-raise-sexp
        paredit-splice-sexp
        sd/join-line
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-alt-done
        ))
