;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        dabbrev-expand
        down-list
        electric-newline-and-maybe-indent
        forward-sexp
        indent-for-tab-command
        indent-new-comment-line
        kill-region
        mark-sexp
        paredit-backward
        paredit-backward-down
        paredit-backward-kill-word
        paredit-backward-up
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-meta-doublequote
        paredit-open-round
        paredit-raise-sexp
        paredit-splice-sexp
        paredit-wrap-round
        sd/join-line
        sgml-slash
        transpose-sexps
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        ivy-alt-done
        ))
